spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/qpos?createDatabaseIfNotExist=true}
    username: ${SPRING_DATABASE_USERNAME:root}
    password: ${SPRING_DATABASE_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver