name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew bootJar
    
    - name: Test if secret exists
      run: |
        echo "Host is set: ${{ secrets.STOQIT_SERVER != '' }}"
        echo "User is set: ${{ secrets.STOQIT_USER != '' }}"
        echo "Pass is set: ${{ secrets.STOQIT_PASSWORD != '' }}"
        if [ -z "${{ secrets.STOQIT_SERVER }}" ]; then
          echo "STOQIT_SERVER is NOT set"
          exit 1
        else
          echo "STOQIT_SERVER is set (length: ${#STOQIT_SERVER})"
        fi
      env:
        STOQIT_SERVER: ${{ secrets.STOQIT_SERVER }}

    - name: Copy JAR to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.STOQIT_SERVER }}
        username: ${{ secrets.STOQIT_USER }}
        password: ${{ secrets.STOQIT_PASSWORD }}
        source: "build/libs/*.jar"
        target: "/home/pos/"
        strip_components: 2
    - name: Restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STOQIT_SERVER }}
        username: ${{ secrets.STOQIT_USER }}
        password: ${{ secrets.STOQIT_PASSWORD }}
        script: /home/pos/restart-app.sh
      
